// middleware.js  —  place at project ROOT (same level as app/, package.json)
//
// Handles all /search-by-make/* routes.
// Returns 410 Gone for every URL that would notFound() in the page component,
// so Googlebot stops crawling dead URLs and crawl budget is preserved.
//
// TRUTH TABLE — Pattern B (/make/model/category/subcategory):
//
//  C# │ makeExcluded │ subcatValid │ seoTrue │ hasProduct │ result
//  ───┼──────────────┼─────────────┼─────────┼────────────┼──────────────
//  ✅ │ No           │ Yes         │ Yes     │ any        │ 200 (render)
//  ✅ │ any          │ any         │ any     │ Yes        │ 200 (product)
//  ───┼──────────────┼─────────────┼─────────┼────────────┼──────────────
//  C1 │ No           │ Yes         │ No      │ No         │ 410
//  C2 │ No           │ No          │ No      │ No         │ 410
//  C3 │ No           │ No          │ Yes     │ No         │ 410
//  C4 │ Yes          │ Yes         │ No      │ No         │ 410
//  C5 │ Yes          │ No          │ No      │ No         │ 410
//  C6 │ Yes          │ No          │ Yes     │ No         │ 410
//  C7 │ Yes          │ Yes         │ Yes     │ No         │ 410

import { NextResponse } from 'next/server';

// Generated by: node scripts/generate-middleware-lookup.mjs
// This file must exist before `next build` runs.
// Add "prebuild": "node scripts/generate-middleware-lookup.mjs" to package.json.
import { VALID_MAKES, MODEL_INDEX, PRODUCT_COMBOS } from './lib/middleware-lookup';

// ─── Static data — keep in sync with your page files ─────────────────────────

const EXCLUDED_MAKES = new Set([
    'Buick', 'Eagle', 'Lotus', 'Plymouth', 'Pontiac', 'Saab', 'Subaru',
    'Alfa Romeo', 'Geo', 'Oldsmobile', 'Isuzu', 'Saturn', 'Corbin', 'Holden',
    'Spyker', 'Spyker Cars', 'Aston Martin', 'Panoz', 'Foose', 'Morgan', 'Aptera',
    'Smart', 'SRT', 'Roush Performance', 'Pagani', 'Mobility Ventures LLC',
    'RUF Automobile', 'Koenigsegg', 'Karma', 'Polestar', 'STI', 'Kandi', 'Abarth',
    'Dorcen', 'Foton', 'W Motors', 'Opel', 'Skoda', 'Hillman', 'Austin', 'Fillmore',
    'Maybach', 'Merkur', 'Rambler', 'Shelby', 'Studebaker', 'Great Wall GWM',
    'Zeekr', 'ZNA', 'GAC', 'Gs7', 'Hongqi', 'W Motor', 'JAC', 'Jaecoo', 'Jetour',
    'TANK', 'Soueast', 'Zarooq Motors', 'Changan', 'Maxus', 'Haval', 'Zotye',
    'Sandstorm', 'Chery', 'Geely', 'BAIC', 'Bestune',
]);

const SELECTED_PARTS = [
    'Battery', 'Engine Assembly', 'Gearbox', 'Radiator',
    'AC Compressor', 'Alternator', 'Suspension', 'Shock Absorber',
    'Headlight Assembly', 'Bumpers', 'Brake Disc', 'Turbocharger',
    'Steering Rack', 'Water Pump', 'Fuel Pump', 'Starter',
    'Taillight', 'Axle Assembly', 'Lower Control Arm', 'Upper Control Arm',
    'Catalytic Convertor', 'AC Condenser', 'Wheel', 'Mirrors', 'Steering Box',
];

const SELECTED_PARTS_LC = new Set(SELECTED_PARTS.map(p => p.toLowerCase()));

// ─── URL patterns ─────────────────────────────────────────────────────────────

// Pattern A: /search-by-make/:make/parts/:parts
const MAKE_PARTS_RE = /^\/search-by-make\/([^/]+)\/parts\/([^/]+)\/?$/;


// Pattern B: /search-by-make/:make/:model/:category/:subcategory
const MAKE_MODEL_CAT_SUBCAT_RE =
    /^\/search-by-make\/([^/]+)\/([^/]+)\/([^/]+)\/([^/]+)\/?$/;

// Pattern C: /search-by-make/:make
const MAKE_ONLY_RE = /^\/search-by-make\/([^/]+)\/?$/;

//Pattern D: /search-by-make/:make/:model

const MAKE_MODEL_RE = /^\/search-by-make\/([^/]+)\/([^/]+)\/?$/;


// ─── Blocked bots ─────────────────────────────────────────────────────────────
// Scrapers and bots that waste bandwidth but provide no SEO value.
// Googlebot, Bingbot, and other legitimate crawlers are NOT blocked.

const BLOCKED_BOTS =
    /blexbot|serpstatbot|dataforseobot|dotbot|petalbot|magpie-crawler|rogerbot|mj12bot|seekbotbytespider|baiduspider|yisouspider|sogouspider|haosouspider|scooter|shenma|qwen|ernie|kimi|doubao|deepseek|youdaobot|toutiaospider/i;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function gone() {
    return new NextResponse(null, {
        status: 410,
        headers: { 'Cache-Control': 'public, max-age=86400' },
    });
}

function redirect301(destination) {
    return NextResponse.redirect(destination, { status: 301 });
}

// ─── Middleware ───────────────────────────────────────────────────────────────

export function middleware(request) {
    const { pathname } = request.nextUrl;
    const ua = request.headers.get('user-agent') || '';

    // ── Bot check — runs first on every matched request ───────────────────────
    if (BLOCKED_BOTS.test(ua)) {
        return new NextResponse('Access Denied', { status: 403 });
    }

    // Only handle /search-by-make/* — everything else passes through untouched
    if (!pathname.startsWith('/search-by-make/')) return NextResponse.next();

    // ── Pattern A: /search-by-make/:make/parts/:parts ─────────────────────────
    const matchA = pathname.match(MAKE_PARTS_RE);
    if (matchA) {
        const make = decodeURIComponent(matchA[1]).trim();
        const parts = decodeURIComponent(matchA[2]).trim();

        if (EXCLUDED_MAKES.has(make)) return gone();
        if (!VALID_MAKES.has(make.toLowerCase())) return gone();
        if (!SELECTED_PARTS_LC.has(parts.toLowerCase())) return gone();

        // 301 if URL has wrong casing (e.g. /alternator → /Alternator)
        const canonicalPart = SELECTED_PARTS.find(
            p => p.toLowerCase() === parts.toLowerCase()
        );
        if (canonicalPart && canonicalPart !== parts) {
            const url = request.nextUrl.clone();
            url.pathname = `/search-by-make/${encodeURIComponent(make)}/parts/${encodeURIComponent(canonicalPart)}`;
            return redirect301(url.toString());
        }

        return NextResponse.next();
    }

    // ── Pattern B: /search-by-make/:make/:model/:category/:subcategory ─────────
    const matchB = pathname.match(MAKE_MODEL_CAT_SUBCAT_RE);
    if (matchB) {
        const make = decodeURIComponent(matchB[1]).trim();
        const model = decodeURIComponent(matchB[2]).trim();
        const category = decodeURIComponent(matchB[3]).trim();
        const subcategory = decodeURIComponent(matchB[4]).trim();

        const makeLc = make.toLowerCase();
        const modelLc = model.toLowerCase();
        const catLc = category.toLowerCase();
        const subLc = subcategory.toLowerCase();

        const makeExcluded = EXCLUDED_MAKES.has(make);
        const makeExists = VALID_MAKES.has(makeLc);

        // Make is completely unknown (not in CarData, not even excluded) → 410
        if (!makeExists && !makeExcluded) return gone();

        const subcatValid = SELECTED_PARTS_LC.has(subLc);
        const seoTrue = MODEL_INDEX[`${makeLc}|${modelLc}`] === 1;

        // Mirrors: const shouldRender = !excluded && subcatValid && hasSEO
        const shouldRender = !makeExcluded && subcatValid && seoTrue;
        if (shouldRender) return NextResponse.next(); // ✅ 200

        // Mirrors: if (!shouldRender && matchingProducts.length === 0) notFound()
        // A product entry saves the page even when shouldRender is false
        const productKey = `${makeLc}|${modelLc}|${catLc}|${subLc}`;
        if (PRODUCT_COMBOS.has(productKey)) return NextResponse.next(); // ✅ 200

        // Nothing saves it — covers all 7 dead conditions (C1–C7)
        return gone(); // ❌ 410
    }

    // ── Pattern C: /search-by-make/:make ──────────────────────────────────────
    const matchC = pathname.match(MAKE_ONLY_RE);
    if (matchC) {
        const make = decodeURIComponent(matchC[1]).trim();
        if (EXCLUDED_MAKES.has(make)) return gone();
        if (!VALID_MAKES.has(make.toLowerCase())) return gone();
        return NextResponse.next();
    }

    // ── Pattern D: /search-by-make/:make/:model  ───────────────────────────────
    const matchD = pathname.match(MAKE_MODEL_RE);
    if (matchD) {
        const make = decodeURIComponent(matchD[1]).trim();
        const model = decodeURIComponent(matchD[2]).trim();

        if (EXCLUDED_MAKES.has(make)) return gone();
        if (!VALID_MAKES.has(make.toLowerCase())) return gone();

        // Model must exist AND have seo:true to have a valid page
        const key = `${make.toLowerCase()}|${model.toLowerCase()}`;
        if (MODEL_INDEX[key] !== 1) return gone();

        return NextResponse.next();
    }

    // Any other /search-by-make/* shape that doesn't match A, B, or C → 410
    return gone();
}

// ─── Matcher ──────────────────────────────────────────────────────────────────
// IMPORTANT: Use ONLY this specific matcher.
// Do NOT add a broad catch-all — it runs middleware on every request
// (HTML, API, images) and multiplies your Vercel invocation bill.

export const config = {
    matcher: ['/search-by-make/:path*'],
};