// middleware.js — place at project ROOT (same level as app/, package.json)
//
// ROUTE PATTERNS HANDLED:
//   A: /search-by-make/:make/parts/:parts
//   B: /search-by-make/:make/:model/:category/:subcategory  ← 410 logic lives here
//   C: /search-by-make/:make
//   D: /search-by-make/:make/:model                         ← always 200 if make is valid
//
// TRUTH TABLE — Pattern B only (/make/model/category/subcategory):
//
//  C# │ makeExcluded │ subcatValid │ seoTrue │ hasProduct │ result
//  ───┼──────────────┼─────────────┼─────────┼────────────┼──────────────
//  ✅ │ No           │ Yes         │ Yes     │ any        │ 200 (render)
//  ✅ │ any          │ any         │ any     │ Yes        │ 200 (product)
//  ───┼──────────────┼─────────────┼─────────┼────────────┼──────────────
//  C1 │ No           │ Yes         │ No      │ No         │ 410
//  C2 │ No           │ No          │ No      │ No         │ 410
//  C3 │ No           │ No          │ Yes     │ No         │ 410
//  C4 │ Yes          │ Yes         │ No      │ No         │ 410
//  C5 │ Yes          │ No          │ No      │ No         │ 410
//  C6 │ Yes          │ No          │ Yes     │ No         │ 410
//  C7 │ Yes          │ Yes         │ Yes     │ No         │ 410

import { NextResponse } from 'next/server';

// Generated by: node scripts/generate-middleware-lookup.mjs
// Must exist before `next build`. Add to package.json:
// "prebuild": "node scripts/generate-middleware-lookup.mjs"
import { VALID_MAKES, MODEL_INDEX, PRODUCT_COMBOS } from './lib/middleware-lookup';

// ─── Static data ──────────────────────────────────────────────────────────────

const EXCLUDED_MAKES = new Set([
    'Buick', 'Eagle', 'Lotus', 'Plymouth', 'Pontiac', 'Saab', 'Subaru',
    'Alfa Romeo', 'Geo', 'Oldsmobile', 'Isuzu', 'Saturn', 'Corbin', 'Holden',
    'Spyker', 'Spyker Cars', 'Aston Martin', 'Panoz', 'Foose', 'Morgan', 'Aptera',
    'Smart', 'SRT', 'Roush Performance', 'Pagani', 'Mobility Ventures LLC',
    'RUF Automobile', 'Koenigsegg', 'Karma', 'Polestar', 'STI', 'Kandi', 'Abarth',
    'Dorcen', 'Foton', 'W Motors', 'Opel', 'Skoda', 'Hillman', 'Austin', 'Fillmore',
    'Maybach', 'Merkur', 'Rambler', 'Shelby', 'Studebaker', 'Great Wall GWM',
    'Zeekr', 'ZNA', 'GAC', 'Gs7', 'Hongqi', 'W Motor', 'JAC', 'Jaecoo', 'Jetour',
    'TANK', 'Soueast', 'Zarooq Motors', 'Changan', 'Maxus', 'Haval', 'Zotye',
    'Sandstorm', 'Chery', 'Geely', 'BAIC', 'Bestune',
]);

const SELECTED_PARTS = [
    'Battery', 'Engine Assembly', 'Gearbox', 'Radiator',
    'AC Compressor', 'Alternator', 'Suspension', 'Shock Absorber',
    'Headlight Assembly', 'Bumpers', 'Brake Disc', 'Turbocharger',
    'Steering Rack', 'Water Pump', 'Fuel Pump', 'Starter',
    'Taillight', 'Axle Assembly', 'Lower Control Arm', 'Upper Control Arm',
    'Catalytic Convertor', 'AC Condenser', 'Wheel', 'Mirrors', 'Steering Box',
];

const SELECTED_PARTS_LC = new Set(SELECTED_PARTS.map(p => p.toLowerCase()));

// ─── URL patterns ─────────────────────────────────────────────────────────────

// NOTE: Order matters — most specific patterns are matched first.
// Pattern B (4 segments) must be checked before Pattern D (2 segments)
// because both could partially match without the anchors.

// A: /search-by-make/:make/parts/:parts
const MAKE_PARTS_RE = /^\/search-by-make\/([^/]+)\/parts\/([^/]+)\/?$/;

// B: /search-by-make/:make/:model/:category/:subcategory  (exactly 4 segments)
const MAKE_MODEL_CAT_SUBCAT_RE =
    /^\/search-by-make\/([^/]+)\/([^/]+)\/([^/]+)\/([^/]+)\/?$/;

// C: /search-by-make/:make  (exactly 1 segment)
const MAKE_ONLY_RE = /^\/search-by-make\/([^/]+)\/?$/;

// D: /search-by-make/:make/:model  (exactly 2 segments)
// seo flag is NOT checked here — model pages always render regardless of seo
const MAKE_MODEL_RE = /^\/search-by-make\/([^/]+)\/([^/]+)\/?$/;

// ─── Blocked bots ─────────────────────────────────────────────────────────────

const BLOCKED_BOTS =
    /blexbot|serpstatbot|dataforseobot|dotbot|petalbot|magpie-crawler|rogerbot|mj12bot|seekbotbytespider|baiduspider|yisouspider|sogouspider|haosouspider|scooter|shenma|qwen|ernie|kimi|doubao|deepseek|youdaobot|toutiaospider/i;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function gone() {
    return new NextResponse(null, {
        status: 410,
        headers: { 'Cache-Control': 'public, max-age=86400' },
    });
}

function redirect301(destination) {
    return NextResponse.redirect(destination, { status: 301 });
}

// ─── Middleware ───────────────────────────────────────────────────────────────

export function middleware(request) {
    const { pathname } = request.nextUrl;
    const ua = request.headers.get('user-agent') || '';

    // Bot check — runs first on every matched request
    if (BLOCKED_BOTS.test(ua)) {
        return new NextResponse('Access Denied', { status: 403 });
    }

    if (!pathname.startsWith('/search-by-make/')) return NextResponse.next();

    // ── Pattern A: /search-by-make/:make/parts/:parts ─────────────────────────
    const matchA = pathname.match(MAKE_PARTS_RE);
    if (matchA) {
        const make = decodeURIComponent(matchA[1]).trim();
        const parts = decodeURIComponent(matchA[2]).trim();

        if (EXCLUDED_MAKES.has(make)) return gone();
        if (!VALID_MAKES.has(make.toLowerCase())) return gone();
        if (!SELECTED_PARTS_LC.has(parts.toLowerCase())) return gone();

        // 301 if URL has wrong casing (e.g. /alternator → /Alternator)
        const canonicalPart = SELECTED_PARTS.find(
            p => p.toLowerCase() === parts.toLowerCase()
        );
        if (canonicalPart && canonicalPart !== parts) {
            const url = request.nextUrl.clone();
            url.pathname = `/search-by-make/${encodeURIComponent(make)}/parts/${encodeURIComponent(canonicalPart)}`;
            return redirect301(url.toString());
        }

        return NextResponse.next();
    }

    // ── Pattern B: /search-by-make/:make/:model/:category/:subcategory ─────────
    const matchB = pathname.match(MAKE_MODEL_CAT_SUBCAT_RE);
    if (matchB) {
        const make = decodeURIComponent(matchB[1]).trim();
        const model = decodeURIComponent(matchB[2]).trim();
        const category = decodeURIComponent(matchB[3]).trim();
        const subcategory = decodeURIComponent(matchB[4]).trim();

        const makeLc = make.toLowerCase();
        const modelLc = model.toLowerCase();
        const catLc = category.toLowerCase();
        const subLc = subcategory.toLowerCase();

        const makeExcluded = EXCLUDED_MAKES.has(make);
        const makeExists = VALID_MAKES.has(makeLc);

        // Make is completely unknown (not in CarData, not excluded) → 410
        if (!makeExists && !makeExcluded) return gone();

        const subcatValid = SELECTED_PARTS_LC.has(subLc);
        const seoTrue = MODEL_INDEX[`${makeLc}|${modelLc}`] === 1;

        // shouldRender = !excluded && subcatValid && seoTrue
        const shouldRender = !makeExcluded && subcatValid && seoTrue;
        if (shouldRender) return NextResponse.next(); // ✅ 200

        // Product match saves the page even when shouldRender is false
        const productKey = `${makeLc}|${modelLc}|${catLc}|${subLc}`;
        if (PRODUCT_COMBOS.has(productKey)) return NextResponse.next(); // ✅ 200

        // Nothing saves it → 410 (covers C1–C7)
        return gone();
    }

    // ── Pattern C: /search-by-make/:make ──────────────────────────────────────
    const matchC = pathname.match(MAKE_ONLY_RE);
    if (matchC) {
        const make = decodeURIComponent(matchC[1]).trim();
        if (EXCLUDED_MAKES.has(make)) return gone();
        if (!VALID_MAKES.has(make.toLowerCase())) return gone();
        return NextResponse.next();
    }

    // ── Pattern D: /search-by-make/:make/:model ────────────────────────────────
    // Model landing page — seo flag is intentionally NOT checked.
    // These pages always render regardless of seo:true/false.
    // Only check that the make itself is valid and not excluded.
    const matchD = pathname.match(MAKE_MODEL_RE);
    if (matchD) {
        const make = decodeURIComponent(matchD[1]).trim();
        const model = decodeURIComponent(matchD[2]).trim();

        if (EXCLUDED_MAKES.has(make)) return gone();
        if (!VALID_MAKES.has(make.toLowerCase())) return gone();

        // Model must at least exist in CarData (seo value doesn't matter)
        const key = `${make.toLowerCase()}|${model.toLowerCase()}`;
        if (MODEL_INDEX[key] === undefined) return gone(); // model not in CarData at all

        return NextResponse.next(); // ✅ 200 — seo:true or seo:false, both pass
    }

    // Any other /search-by-make/* shape → 410
    return gone();
}

export const config = {
    matcher: ['/search-by-make/:path*'],
};